### ISSUE TITLE
Section heeft een heading nodig

### ISSUE THREAD

**Issue by KoopReynders** [julesbruins/the-client-website#11]
https://github.com/julesbruins/the-client-website/blob/c15e71e0fd6dccdd15d17e7713723604f6144ea5/index.html#L47

Een section heeft altijd een heading nodig. Als dat niet perse hoeft, maar je wil verschillende articles groeperen, dan kun je beter een ander element gebruiken. 

> The <section> HTML element represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

**Comment by julesbruins** [comment]
Wat voor element kan ik dan beter gebruiken denkt u?

**Comment by KoopReynders** [comment]
-excuus, mijn comment was niet helmaal goed doorgekomen- 

Ik probeerde je dit te leren: 

> The `<section>` HTML element represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

Oftewel: 
Je kan daar prima een `<section>` gebruiken om verschillende artikelen in te nesten, maar dan heeft je `<section>` wel een heading nodig. Als er geen heading nodig is op die plak, dan moet je overwerken om een ander element te gebruiken om de artikelen te nesten.

**Comment by julesbruins** [comment]
Van de section een div gemaakt, dus aangepast want er was geen heading nodig het was alleen voor styling.
13d5e6bf0b519e1f55786b138b919fee054b722b
