### ISSUE TITLE
Elementen sluiten in de nav

### ISSUE THREAD

**Issue by zainablfz** [julesbruins/the-client-website#13]
https://github.com/julesbruins/the-client-website/blob/6dd22a6e8d534620dc63e06aa951b36ceb1f7bf6/index.html#L34-L35

Je hebt netjes gebruik gemaakt van semantische elementen in de nav. Alleen let goed op dat je de `ul` goed sluit in de `nav`, nu staat het erbuiten.

**Comment by julesbruins** [comment]
done 280d5bbba38ca429391034d664973f89ce0c97ac
