### ISSUE TITLE
Verkeerde taal ingesteld in de head 

### ISSUE THREAD

**Issue by zainablfz** [julesbruins/the-client-website#14]
https://github.com/julesbruins/the-client-website/blob/6dd22a6e8d534620dc63e06aa951b36ceb1f7bf6/index.html#L2

Wanneer de content van de website niet in het Engels is, moet je dit veranderen naar de bijbehorende taal. In dit geval is de website in het Nederlands. 

Het is een kleine en snelle aanpassing, maar wel heel belangrijk voor o.a. screenreaders 🙃

**Comment by julesbruins** [comment]
done ef4386bb7fc632d434ddbabf976d5e7cb7b18cc4
