### ISSUE TITLE
Herhaling in CSS code 

### ISSUE THREAD

**Issue by zainablfz** [julesbruins/the-client-website#16]
https://github.com/julesbruins/the-client-website/blob/6dd22a6e8d534620dc63e06aa951b36ceb1f7bf6/styles/styles.css#L46-L61

Je bent goed op weg met je CSS! Ik merk alleen wel dat je veel herhaling hebt in het bestand. Dat betekent natuurlijk een langer bestand en meer lezen/schrijven. 

Je kan om herhaling te voorkomen de `<a>` element een styling geven, zoals de font-family, font-size, etc. die bij beide hetzelfde zijn en dan bij de classes de styling te geven die anders moeten zijn, zoals de kleur.

**Comment by julesbruins** [comment]
done 3d2270b937e0c1141cfb3d79dc7785932ca20e24
