### ISSUE TITLE
Alt attribute "logo" voor logo image

### ISSUE THREAD

**Issue by KoopReynders** [julesbruins/the-client-website#8]
https://github.com/julesbruins/the-client-website/blob/c15e71e0fd6dccdd15d17e7713723604f6144ea5/index.html#L14

Waar is het alt attribuut voor nodig?
Nu staat er 'logo' maar een gebruiker ziet het logo in de website?

**Comment by julesbruins** [comment]
Ik heb hem de alt 'logo' gegeven. Ik dacht dat je afbeeldingen altijd een alt moest geven in geval de site niet de afbeeldingen laadde of voor mensen die de site laten oplezen?

**Comment by KoopReynders** [comment]
Klopt, een afbeelding heef een alt nodig, maar wat zet je daarin !?!
Als een screen reader wordt gebruikt wordt er 'logo' opgelezen, wat heeft de gebruiker daaraan?

Hier staat een mooie uitleg over alt 'design':  https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by julesbruins** [comment]
aangepast!
a62adfb0ac5ac484ae2993321a5c8f03268a1f3d
